### ISSUE TITLE
hotfix download failed 从BUGLY接入的，这个是个什么意思，度娘也搜不到类似的

### ISSUE THREAD

**Issue by mpeng5120** [simpleton/tiny_httpclient#102]
8-20 13:49:40.613 26704-26704/com.jifenzhi.enterprise E/CrashReport: hotfix download failed：(2020)java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-20 13:49:40.670 26704-26930/com.jifenzhi.enterprise W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-20 13:49:40.671 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:361)
08-20 13:49:40.671 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.okhttp.Connection.connectTls(Connection.java:235)
08-20 13:49:40.671 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.okhttp.Connection.connectSocket(Connection.java:199)
08-20 13:49:40.672 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:172)
08-20 13:49:40.672 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
08-20 13:49:40.672 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
08-20 13:49:40.672 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
08-20 13:49:40.672 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
08-20 13:49:40.672 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
08-20 13:49:40.673 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
08-20 13:49:40.673 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
08-20 13:49:40.673 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
08-20 13:49:40.673 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.tencent.bugly.proguard.t.run(BUGLY:188)
08-20 13:49:40.673 26704-26930/com.jifenzhi.enterprise W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
08-20 13:49:40.673 26704-26930/com.jifenzhi.enterprise W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-20 13:49:40.673 26704-26930/com.jifenzhi.enterprise W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
08-20 13:49:40.673 26704-26930/com.jifenzhi.enterprise W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-20 13:49:40.673 26704-26930/com.jifenzhi.enterprise W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-20 13:49:40.673 26704-26930/com.jifenzhi.enterprise W/System.err:     at java.lang.Thread.run(Thread.java:761)
08-20 13:49:40.674 26704-26930/com.jifenzhi.enterprise W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-20 13:49:40.674 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
08-20 13:49:40.674 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:401)
08-20 13:49:40.674 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
08-20 13:49:40.674 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
08-20 13:49:40.675 26704-26930/com.jifenzhi.enterprise W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
08-20 13:49:40.675 26704-26930/com.jifenzhi.enterprise W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
08-20 13:49:40.675 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
08-20 13:49:40.675 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:596)
08-20 13:49:40.675 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
08-20 13:49:40.675 26704-26930/com.jifenzhi.enterprise W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
08-20 13:49:40.675 26704-26930/com.jifenzhi.enterprise W/System.err: 	... 18 more
08-20 13:49:40.676 26704-26930/com.jifenzhi.enterprise W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
08-20 13:49:40.676 26704-26930/com.jifenzhi.enterprise W/System.err: 	... 28 more
08-20 13:49:40.676 26704-26930/com.jifenzhi.enterprise D/CrashReport: [t] IOException,stop download!
08-20 13:49:40.677 26704-26930/com.jifenzhi.enterprise D/CrashReport: [t] have retry 3 times
08-20 13:49:40.684 26704-26704/com.jifenzhi.enterprise D/CrashReport: [Database] insert ge_1002 success.
08-20 13:49:40.684 26704-26704/com.jifenzhi.enterprise E/CrashReport: hotfix download failed：(2020)java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by simpleton** [comment]
Bugly的问题建议直接联系Bugly客服或者开发同学
