### ISSUE TITLE
tinkerpatch加载补丁的时候出现错误码 -101

### ISSUE THREAD

**Issue by yilugesanghua** [simpleton/tiny_httpclient#104]
@上线版本出现一个用户在加载补丁的时候进入安全模式后失败 ，patch后台给出来的日志是：错误码：-101，错误提示：补丁加载进入安全模式 @bang590 @simpleton @shwenzhang

**Comment by yilugesanghua** [comment]
![image](https://user-images.githubusercontent.com/5662065/44580576-ff1c1e80-a7cc-11e8-8454-d14a19749460.png)

**Comment by simpleton** [comment]
可以查看文档了解安全模式，如果是debug的话，可以提供一下手机运行的log方便debug.
