### ISSUE TITLE
大佬求助啊，配置应该都是对的，但是总是提示PatchRequestCallback: Plz make sure you fill the correct appVersion and appKey in tinkerpatch.gradle. Or create the correspond project in tinkerpatch.com

### ISSUE THREAD

**Issue by fafala** [simpleton/tiny_httpclient#122]
**sdk版本**：com.tinkerpatch.sdk:tinkerpatch-android-sdk:1.2.11
**测试环境**：Android6.0
**运行程序是强制检测补丁：** TinkerPatch.with().fetchPatchUpdate(true);
**测试版本使用命令：**assembleDebug，tinkerPatchDebug.测试的时候使用了DebugTool，开关为“开发模式”
截图**：控制台配置**
![image](https://user-images.githubusercontent.com/12274717/55533799-08ffeb80-56e5-11e9-8f1e-a50096390e31.png)
application中的初始化：
![image](https://user-images.githubusercontent.com/12274717/55533933-6f850980-56e5-11e9-984b-784ca4438a35.png)
**日志：**
04-04 14:26:28.533 9655-9655/  W/Tinker.TinkerLoader: tryLoadPatchFiles:patch dir not exist:/data/user/0/ /tinker
04-04 14:26:28.539 9655-9655/  D/Tinker.DefaultAppLike: onBaseContextAttached:
04-04 14:26:28.540 9655-9655/  I/Tinker.ReflectApp: with app application from manifest applicationName: .app.AppStudio
04-04 14:26:28.551 9655-9655/  I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
04-04 14:26:28.596 9655-9655/  I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
04-04 14:26:28.596 9655-9655/  D/Tinker.DefaultAppLike: onCreate
04-04 14:26:28.921 9655-9655/  I/Tinker.ServerUtils: with app key from manifest appKey:29c623831ddffc1d
04-04 14:26:28.921 9655-9655/  I/Tinker.ServerUtils: with app version from manifest appVersion:2.03_xiaomaCharge
04-04 14:26:28.931 9655-9655/  I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/ /tinker_server/29c623831ddffc1d_version.info, appVersion: 2.03_xiaomaCharge, uuid:c8f8ddf3-f2cf-4b31-b831-4a3c03dfcaa4, abi:armeabi-v7a, patchVersion:0, patchMd5:, grayValue:6, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
04-04 14:26:28.953 9655-9655/  I/Tinker.Debugger: debugger attached
04-04 14:26:28.956 9655-9655/  D/Tinker.Debugger: getBoolean(): key=.com.tinker.debugtool.debug, value=true
04-04 14:26:28.956 9655-9655/  I/Tinker.ServerClient: installTinkerServer, debug value: true, appVersion: 2.03_xiaomaCharge, appKey: 29c623831ddffc1d
04-04 14:26:28.960 9655-9655/  W/Tinker.Tinker: tinker patch directory: /data/user/0/ /tinker
04-04 14:26:28.962 9655-9655/  I/art: Rejecting re-init on previously-failed class java.lang.Class<com.tencent.tinker.lib.util.TinkerJobIntentService$JobServiceEngineImpl>
04-04 14:26:28.962 9655-9655/  I/art: Rejecting re-init on previously-failed class java.lang.Class<com.tencent.tinker.lib.util.TinkerJobIntentService$JobServiceEngineImpl>
04-04 14:26:28.966 9655-9655/  I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.11
04-04 14:26:28.967 9655-9655/  I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-2, process name: , main process:true, systemOTA:false, fingerPrint:Xiaomi/cancro_wc_lte/cancro:6.0.1/MMB29M/V10.1.1.0.MXDCNFI:user/release-keys, oatDir:null, useInterpretMode:false
04-04 14:26:28.967 9655-9655/  W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
04-04 14:26:28.967 9655-9655/  I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/ /tinker, code: -2, cost: 5ms
04-04 14:26:28.967 9655-9655/  W/Tinker.Tinker: tinker load fail!
04-04 14:26:28.967 9655-9655/  I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.11
04-04 14:26:28.968 9655-9655/  E/ZYH_TAG: Thread: main
    	─  .app.AppStudio.initTinkerPatch(AppStudio.java:73)
     微信热更新补丁版本 = 0
04-04 14:26:29.473 9655-9655/  W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return
04-04 14:26:29.477 9655-9655/  W/Tinker.ClientImpl: [retryAllReportFails], there is no fail report, just return
04-04 14:26:29.495 9655-9655/  I/Tinker.UrlConnectionFetcher: loadData from url: http://q.tinkerpatch.com/dev/29c623831ddffc1d/2.03_xiaomaCharge?d=c8f8ddf3-f2cf-4b31-b831-4a3c03dfcaa4&v=1554359189494, method:GET, body:null
04-04 14:26:29.725 9655-9711/  I/Tinker.UrlConnectionFetcher: response code 404 msg: Not Found
04-04 14:26:29.725 9655-9711/  W/Tinker.PatchRequestCallback: TinkerPatchRequestCallback onPatchSyncFail error: java.io.FileNotFoundException: http://q.tinkerpatch.com/dev/29c623831ddffc1d/2.03_xiaomaCharge?d=c8f8ddf3-f2cf-4b31-b831-4a3c03dfcaa4&v=1554359189494
04-04 14:26:29.725 9655-9711/  E/Tinker.PatchRequestCallback: Plz make sure you fill the correct appVersion and appKey in tinkerpatch.gradle. Or create the correspond project in tinkerpatch.com

**错误：**### TinkerPatchRequestCallback onPatchSyncFail error: java.io.FileNotFoundException: http://q.tinkerpatch.com/dev/29c623831ddffc1d/2.03_xiaomaCharge?d=c8f8ddf3-f2cf-4b31-b831-4a3c03dfcaa4&v=1554359189494
Tinker.PatchRequestCallback: Plz make sure you fill the correct appVersion and appKey in tinkerpatch.gradle. Or create the correspond project in tinkerpatch.com

**为什么请求不到补丁，404啊**

**Comment by fafala** [comment]
自己书写的问题

**Comment by simpleton** [comment]
[image: image.png]

版本号写错了
04-04 14:26:28.956 9655-9655/ I/Tinker.ServerClient: installTinkerServer, debug value: true, appVersion: 2.03_xiaomaCharge, appKey: 29c623831ddffc1d
