### ISSUE TITLE
tinker热更新，是否支持android项目证书更吗？

### ISSUE THREAD

**Issue by 1025798432** [simpleton/tiny_httpclient#123]

**Comment by simpleton** [comment]
不支持

**Comment by 1025798432** [comment]
不支持，有什么办法可以解决证书更新的问题吗？已经上线的app，现在更换证书后，如何覆盖安装？
谢谢了。




------------------ 原始邮件 ------------------
发件人: "Sim Sun"<notifications@github.com>;
发送时间: 2019年4月11日(星期四) 中午11:26
收件人: "TinkerPatch/tinkerpatch-sdk"<tinkerpatch-sdk@noreply.github.com>;
抄送: "科伦坡"<1025798432@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [TinkerPatch/tinkerpatch-sdk] tinker热更新，是否支持android项目证书更吗？ (#123)




不支持
