### ISSUE TITLE
联系不上客服

### ISSUE THREAD

**Issue by mutoujun** [simpleton/tiny_httpclient#137]
请问贵司是什么自闭公司？？？联系我们一定要邮箱才能联系，我的电脑默认邮箱插件都没有，是不是就联系不上你们了？？？好不容易找到一台有邮箱插件的，结果一直都无法验证用户名或密码！！！你们作为国内这么大的一个热修复平台，连个像样的客服都没有，叫天天不应，叫地地不灵的。还有标准版都说明了有1对1问题服务的，我花了钱了，人呢？？？服务呢？？？这么自闭？？？还有文档里的官方QQ群都是不存在？？？你们到底是怎么做的服务公司，服务差到这种地方，真是人生第一次见，气死人了！！！

**Comment by simpleton** [comment]
你遇到什么问题么？

**Comment by mutoujun** [comment]
问题已发送至您邮箱，望查看
