### ISSUE TITLE
使用1.9.13tinker下发后9.0出现很多崩溃

### ISSUE THREAD

**Issue by dyp021** [simpleton/tiny_httpclient#138]
存在的问题
1，各种xml资源包找不到
2，ava.lang.IncompatibleClassChangeError
Class 'org.apache.http.impl.client.DefaultProxyAuthenticationHandler' does not implement interface 'org.apache.http.params.HttpParams' in call to 'org.apache.http.params.HttpParams org.apache.http.params.HttpParams.setLongParameter(java.lang.String, long)' (declaration of 'org.apache.http.conn.params.ConnManagerParams' appears in /system/framework/org.apache.http.legacy.boot.jar)

现在最新tinker是1.9.13.2，但是tinkerpatch不支持，麻烦请尽快支持 tinker的1.9.13.2版本
谢谢

**Comment by simpleton** [comment]
Fixed. 可以尝试下[`1.2.13.2`](https://bintray.com/simsun/maven/tinkerpatch-android-sdk/1.2.13.2)

**Comment by iceAnson** [comment]
> Fixed. 可以尝试下[`1.2.13.2`](https://bintray.com/simsun/maven/tinkerpatch-android-sdk/1.2.13.2)

使用1.9.14还是会出现：
Class 'java.lang.String' does not implement interface 'org.apache.http.HttpResponse' in call to 'org.apache.http.StatusLine org.apache.http.HttpResponse.getStatusLine()' (declaration of 'org.apache.http.impl.client.DefaultProxyAuthenticationHandler' appears in /system/framework/org.apache.http.legacy.boot.jar)
