### ISSUE TITLE
放弃使用了

### ISSUE THREAD

**Issue by a8stefan** [simpleton/tiny_httpclient#159]

**Comment by simpleton** [comment]
使用中有什么问题么

**Comment by a8stefan** [comment]
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA
java.io.IOException: Can't Generate signed APK. Please check if your sign info is correct.

Signing key algorithm is SHA1withRSA   这个需要SHA1withRSA签名算法 . 我的jks签名算法SHA256withRSA . 怎么样兼容

**Comment by a8stefan** [comment]
classpath 'com.android.tools.build:gradle:3.1.2'  和mac     电脑和gradle有关系吗？

**Comment by a8stefan** [comment]
@simpleton

**Comment by simpleton** [comment]
n你是如何生成的key呢 我这边尝试复现一下问题

**Comment by a8stefan** [comment]
我写个demo发你可好

**Comment by a8stefan** [comment]
你的tinker-sample-android项目 我先gradle 里面先assembleRelease 打出基础包,基础包配置：baseInfo ，然后继续执行tinkerPatchRelease  
 Gen classes.dex patch file:/Users/jerrychang/Desktop/tinkerpatch-easy-sample-master-2/app/build/outputs/apk/tinkerPatch/release/tinker_result/classes.dex, size:542, md5:122a75730a048d6079cb4e02bf82baab
Verifying if patched new dex is logically the same as original new dex: app-release-new/classes.dex ...

Gen classes.dex for dalvik full dex file:/Users/jerrychang/Desktop/tinkerpatch-easy-sample-master-2/app/build/outputs/apk/tinkerPatch/release/tempPatchedDexes/classes.dex, size:1110160, md5:3aa96a6b5ccaa62c12d6f433dc6eae78
DexDecoder:write meta file data: classes.dex,,3aa96a6b5ccaa62c12d6f433dc6eae78,3aa96a6b5ccaa62c12d6f433dc6eae78,122a75730a048d6079cb4e02bf82baab,788889163,1095332664,jar

Add test install result dex: /Users/jerrychang/Desktop/tinkerpatch-easy-sample-master-2/app/build/outputs/apk/tinkerPatch/release/tinker_result/test.dex, size:584
DexDecoder:write test dex meta file data: test.dex,,56900442eb5b7e1de45449d0685e6e00,56900442eb5b7e1de45449d0685e6e00,0,0,0,jar
Generate unsigned apk: patch_unsigned.apk
Signing apk: patch_signed.apk
Signing key algorithm is SHA1withRSA
13:50:38: Task execution finished 'tinkerPatchRelease'.
最后没有打出  patch_signed.apk这个包

**Comment by a8stefan** [comment]
别名: android.keystore
创建日期: 2017-7-12
条目类型: PrivateKeyEntry
证书链长度: 3
证书[1]:
所有者: CN=王沛茗, EMAILADDRESS=283859701@qq.com, OU=2_个人开发者证书, O=王沛茗, L=绵阳市, ST=四川省, C=CN
发布者: CN=WoSign IV Code Signing CA for Android, O=WoSign CA Limited, C=CN
序列号: 30fae028e11ea4c601986bd7445c89b4
有效期为 Wed Jul 12 17:04:45 PST 2017 至 Sun Jul 12 17:04:45 PST 2037
证书指纹:
	 MD5:  82:9D:C0:56:5E:53:75:05:52:57:DD:00:03:AA:F5:FC
	 SHA1: 79:12:9D:29:04:0E:37:94:AC:FE:9F:8A:40:31:ED:BF:38:AB:67:84
	 SHA256: DF:6C:8D:32:5F:38:AC:17:B3:67:97:92:AA:7D:63:C8:50:93:EC:9B:39:B0:D1:EA:7E:BC:DD:4F:A2:70:3D:41
签名算法名称: SHA256withRSA
主体公共密钥算法: 2048 位 RSA 密钥
版本: 3

扩展: 

#1: ObjectId: 1.3.6.1.5.5.7.1.1 Criticality=false
AuthorityInfoAccess [
  [
   accessMethod: ocsp
   accessLocation: URIName: http://ocsp1.wosign.com/class2/code/android
, 
   accessMethod: caIssuers
   accessLocation: URIName: http://aia1.wosign.com/code2.ca5.android.cer
]
]

#2: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: E0 38 90 E8 97 84 38 D9   00 85 A0 BD 44 04 3F 01  .8....8.....D.?.
0010: 26 74 EB E0                                        &t..
]
]

#3: ObjectId: 2.5.29.19 Criticality=false
BasicConstraints:[
  CA:false
  PathLen: undefined
]

#4: ObjectId: 2.5.29.31 Criticality=false
CRLDistributionPoints [
  [DistributionPoint:
     [URIName: http://crls1.wosign.com/ca5-code2-android.crl]
]]

#5: ObjectId: 2.5.29.32 Criticality=false
CertificatePolicies [
  [CertificatePolicyId: [2.23.140.1.4.1]
[]  ]
  [CertificatePolicyId: [1.3.6.1.4.1.36305.1.1.2]
[PolicyQualifierInfo: [
  qualifierID: 1.3.6.1.5.5.7.2.1
  qualifier: 0000: 16 1D 68 74 74 70 3A 2F   2F 77 77 77 2E 77 6F 73  ..http://www.wos
0010: 69 67 6E 2E 63 6F 6D 2F   70 6F 6C 69 63 79 2F     ign.com/policy/

]]  ]
]

#6: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  codeSigning
  clientAuth
]

#7: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  DigitalSignature
]

#8: ObjectId: 2.5.29.17 Criticality=false
SubjectAlternativeName [
  RFC822Name: 283859701@qq.com
]

#9: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: C9 7C 71 3E 04 2D 3B D8   6D A9 DC B7 C8 C8 E5 90  ..q>.-;.m.......
0010: DB 9C 6B 70                                        ..kp
]
]

证书[2]:
所有者: CN=WoSign IV Code Signing CA for Android, O=WoSign CA Limited, C=CN
发布者: CN=China Root of WoSign, O=WoSign CA Limited, C=CN
序列号: 2b4b0dc8a2da63930f3ec02fd9ddeffb
有效期为 Wed Jun 18 09:00:05 PST 2014 至 Sat Jun 18 09:00:05 PST 2044
证书指纹:
	 MD5:  86:86:D5:5B:C6:AA:AE:18:25:5A:47:EC:3C:F5:6D:DB
	 SHA1: D3:6F:23:D0:25:FF:D2:3A:EF:AD:97:7C:F6:D1:35:C6:03:55:72:8C
	 SHA256: C7:2B:15:98:27:8B:D5:3C:90:93:89:56:8B:00:D7:FB:5A:88:3B:7A:FA:E0:33:AE:2F:53:B2:27:81:EB:75:22
签名算法名称: SHA1withRSA
主体公共密钥算法: 2048 位 RSA 密钥
版本: 3

扩展: 

#1: ObjectId: 1.3.6.1.5.5.7.1.1 Criticality=false
AuthorityInfoAccess [
  [
   accessMethod: ocsp
   accessLocation: URIName: http://ocsp5.wosign.com/ca5
, 
   accessMethod: caIssuers
   accessLocation: URIName: http://aia5.wosign.com/ca5-code2-android.cer
]
]

#2: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: C4 AC 3D 6B F6 22 D4 15   B4 87 BB 80 72 94 B0 DB  ..=k."......r...
0010: 10 02 A6 F3                                        ....
]
]

#3: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:0
]

#4: ObjectId: 2.5.29.31 Criticality=false
CRLDistributionPoints [
  [DistributionPoint:
     [URIName: http://crls5.wosign.com/ca5.crl]
]]

#5: ObjectId: 2.5.29.32 Criticality=false
CertificatePolicies [
  [CertificatePolicyId: [1.3.6.1.4.1.36305.5.2.3.4]
[PolicyQualifierInfo: [
  qualifierID: 1.3.6.1.5.5.7.2.1
  qualifier: 0000: 16 1D 68 74 74 70 3A 2F   2F 77 77 77 2E 77 6F 73  ..http://www.wos
0010: 69 67 6E 2E 63 6F 6D 2F   70 6F 6C 69 63 79 2F     ign.com/policy/

]]  ]
]

#6: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  codeSigning
]

#7: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#8: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: E0 38 90 E8 97 84 38 D9   00 85 A0 BD 44 04 3F 01  .8....8.....D.?.
0010: 26 74 EB E0                                        &t..
]
]

证书[3]:
所有者: CN=China Root of WoSign, O=WoSign CA Limited, C=CN
发布者: CN=China Root of WoSign, O=WoSign CA Limited, C=CN
序列号: 3b8fc52c3be60322904500006f536649
有效期为 Wed Jun 18 09:00:01 PST 2014 至 Sat Jun 18 09:00:09 PST 2044
证书指纹:
	 MD5:  86:DA:A4:5A:08:75:BF:D7:17:A0:E6:99:2C:B8:B5:2A
	 SHA1: 7D:49:E5:8E:D2:C6:A3:E1:F9:85:38:C7:40:DD:11:26:53:9B:25:07
	 SHA256: F4:0C:4D:AA:62:B4:DC:91:73:8C:56:F2:23:67:9F:E6:FE:A5:20:7A:46:32:0E:77:B8:12:21:37:8B:68:0B:D9
签名算法名称: SHA1withRSA
主体公共密钥算法: 2048 位 RSA 密钥
版本: 3

扩展: 

#1: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#2: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#3: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: C4 AC 3D 6B F6 22 D4 15   B4 87 BB 80 72 94 B0 DB  ..=k."......r...
0010: 10 02 A6 F3                                        ....
]
]
这个是你demo里面的keystore

**Comment by a8stefan** [comment]
已经解决

**Comment by 1136346879** [comment]
哥们如何解决的  ？ 你能详述一下吗，是什么原因
