### ISSUE TITLE
发布包和基准包和补丁包 都是什么概念？

### ISSUE THREAD

**Issue by 1136346879** [simpleton/tiny_httpclient#162]
我发布各大安卓应用市场的包是我以前的打包方式吗？还是用基准包去发布？

补丁包是在基准包的基础上改动代码修复BUG后才去生成吗？

**Comment by simpleton** [comment]
是的，发布的都是基准包。补丁包总是使用基准包生成

**Comment by 1136346879** [comment]
现在各大市场 都需要加固签名  是用基准包去用360加固或乐固加固签名  再发布市场吗？
谢谢楼主

**Comment by simpleton** [comment]
http://tinkerpatch.com/Docs/SDK
可以查看一下加固的相关章节
