### ISSUE TITLE
Tinker的1.9.14.4版本因为有问题已经没有发布了，但是TinkerPath最新版本还是基于1.9.14.4

### ISSUE THREAD

**Issue by alen252** [simpleton/tiny_httpclient#170]
Tinker的1.9.14.4版本因为有问题已经没有发布了，但是TinkerPath最新版本还是基于1.9.14.4。
其实Tinker已经出了1.9.14.5版本，你们需要基于这个最新版本发布下

**Comment by simpleton** [comment]
收到 我今天更新 测试下

**Comment by simpleton** [comment]
http://tinkerpatch.com/Docs/changelog
