### ISSUE TITLE
关于tinker对于odex的支持的疑问

### ISSUE THREAD

**Issue by sherlockwep** [simpleton/tiny_httpclient#77]
请问一下，tinker对于系统级app（经过了odex优化的），是否支持？
如果支持，对于一个被odex优化的系统级app，如何来生成增量patch包？

**Comment by simpleton** [comment]
如果已经odex过了，应该是不支持的。tinker也没有在这种情况下充分测试过，建议不要使用。

**Comment by simpleton** [comment]
cc @shwenzhang @tomystang

**Comment by sherlockwep** [comment]
感谢反馈！
