### ISSUE TITLE
使用了productFlavors，同一版本覆盖渠道，导致补丁无效

### ISSUE THREAD

**Issue by ArcherLucky** [simpleton/tiny_httpclient#80]
appVersion 是 版本号_渠道名 ，例：3.0.0_tencent，3.0.0_xiaomi
设备先安装3.0.0_tencent的基准包，下载-应用补丁，正常
随后**覆盖为同版本不同渠道**3 如：3.0.0_xiaomi的基准包，下载正常，但补丁应用不上，也修复不了
（卸载重装后，正常）

**Comment by simpleton** [comment]
可以贴一下相关错误LOG么？

**Comment by ArcherLucky** [comment]
没办法贴了，我又试了几次，又没有问题了
