### ISSUE TITLE
红米1s出现的问题

### ISSUE THREAD

**Issue by 17771436337** [simpleton/tiny_httpclient#83]
05-21 18:09:36.255 24060-24060/cn.lovingart.livecloud E/SIMICO: Thread[main,5,main], Cause By:java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
    
    cn.lovingart.livecloud.activity.ClassWebActivity$$ViewBinder.bind(ClassWebActivity$$ViewBinder.java:12)
    butterknife.ButterKnife.bind(ButterKnife.java:187)
    butterknife.ButterKnife.bind(ButterKnife.java:122)
    cn.lovingart.livecloud.activity.ClassWebActivity.onCreate(ClassWebActivity.java:94)
    android.app.Activity.performCreate(Activity.java:5242)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2249)
    android.app.ActivityThread.access$800(ActivityThread.java:141)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1212)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:136)
    android.app.ActivityThread.main(ActivityThread.java:5113)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
    dalvik.system.NativeStart.main(Native Method)

打上补丁后，在其他手机上都没有任何问题，但是在红米4.4.4版本上会出现这个问题？？？

**Comment by simpleton** [comment]
你可以尝试下sample是否也出现问题，排查一下是配置问题还是库本身的问题：
https://github.com/TinkerPatch/tinkerpatch-easy-sample
