### ISSUE TITLE
编译时候报错package does not exist

### ISSUE THREAD

**Issue by skyEnlong** [simpleton/tiny_httpclient#84]
编译过程中报；
error: package com.tencent.tinker.loader.app does not exist
import com.tencent.tinker.loader.app.TinkerApplication;

**Comment by simpleton** [comment]
可以贴一下你的相关配置文件么？比如使用的版本，引入的依赖

**Comment by simpleton** [comment]
可以参考一下这个sample: https://github.com/TinkerPatch/tinkerpatch-easy-sample
