### ISSUE TITLE
关于4.x系列安卓版的问题

### ISSUE THREAD

**Issue by cvvbbo** [simpleton/tiny_httpclient#86]
5.0~8.0的安卓系统，上传补丁后，再新安装应用，启动之后立马从后台划掉，再次启动能看到补丁效果。但是4.x安卓版本的手机，在新安装应用后从后台划掉再启动不能看到立马补丁效果，还是要说要等fetchPatchWithInterval()方法里面的设置时间？

**Comment by simpleton** [comment]
所有版本如果没安装debugtools 都需要等待这个时间的。但是首次安装或者卸载重新安装第一次是不需要的。
没成功的原因还是具体看下Log吧
