### ISSUE TITLE
发布新的补丁是否需要修改appVersion

### ISSUE THREAD

**Issue by zhaoziliang01** [simpleton/tiny_httpclient#87]
我在别人的博客中看到发布新补丁前需要修改tinkerpatch.gradle中的appVersion，但我实际实验的时候发现修改与不修改都可以实现热修复。到底需不需要发布新补丁前修改tinkerpatch.gradle中的appVersion呢?

**Comment by simpleton** [comment]
@zhaoziliang01 http://tinkerpatch.com/Docs/SDK 这里有step by step的文档。更改appVersion是为了区分不同基础包，如果不更新会无法区分。

**Comment by zhaoziliang01** [comment]
@simpleton 你好，那生成补丁包的时候appVersion是否需要更新呢？文档没说到这个

**Comment by simpleton** [comment]
appVersion和本身tinker的合成流程无关，但是为了方便管理建议每次去应用商店发布新包都更新此值。
> TinkerPatch SDK 采用的 TinkerId？
TinkerPatch SDK 默认采用 appVersion 作为 TinkerId, 我们需要保证每个发布出去的基准安装包的 appVersion 都不一致。
我们可以使用 versionName 或者 githash 作为 appVersion.

**Comment by zhaoziliang01** [comment]
好的谢谢
