### ISSUE TITLE
你的账号属于10w量级，请先升级到标准版。

### ISSUE THREAD

**Issue by yelustyle** [simpleton/tiny_httpclient#91]
第一次放生产包的补丁，就提示这个，不是说好补丁不超过500K就能使用成功？

**Comment by simpleton** [comment]
http://tinkerpatch.com/Price
日请求量也是限制，首月是无限制免费体验的。如果你之前注册了，但是一直没有使用，你可以提供一下你的邮箱。我这边给你去除一下限制。
