### ISSUE TITLE
下载了补丁包之后，遇到了“patch info not exist”，导致更新失败，请问是什么问题？Log如下：

### ISSUE THREAD

**Issue by DengZhouLi** [simpleton/tiny_httpclient#92]
机型：小米6
Log：
06-22 20:27:20.442 32103-32237/xyz.nesting.tinkerdemo I/Tinker.UrlConnectionFetcher: response code 200 msg: OK
06-22 20:27:20.462 32103-32237/xyz.nesting.tinkerdemo D/Tinker.ClientImpl: [succ] report successfully with url: http://stat.tinkerpatch.com/succ.php, body: sv=1.2.5&t=1&av=1.0.0&ch=Null&pv=2&k=e1b91ce001a2a7b0 reportingCount: 0, fail pool size: 0
06-22 20:28:26.098 459-459/xyz.nesting.tinkerdemo W/Tinker.TinkerLoader: tryLoadPatchFiles:patch info not exist:/data/user/0/xyz.nesting.tinkerdemo/tinker
06-22 20:28:26.098 459-459/xyz.nesting.tinkerdemo D/Tinker.DefaultAppLike: onBaseContextAttached:
06-22 20:28:26.099 459-459/xyz.nesting.tinkerdemo I/Tinker.ReflectApp: with app application from manifest applicationName:xyz.nesting.tinkerdemo.MyApplication
06-22 20:28:26.099 459-459/xyz.nesting.tinkerdemo I/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tinkerpatch.sdk.loader.TinkerPatchApplicationLike
06-22 20:28:26.101 459-459/xyz.nesting.tinkerdemo I/Tinker.ComponentHotplug: method install() is not invoked, ignore ensuring operations.
06-22 20:28:26.101 459-459/xyz.nesting.tinkerdemo D/Tinker.DefaultAppLike: onCreate
06-22 20:28:26.103 459-459/xyz.nesting.tinkerdemo I/Tinker.ServerUtils: with app key from manifest appKey:e1b91ce001a2a7b0
06-22 20:28:26.104 459-459/xyz.nesting.tinkerdemo I/Tinker.ServerUtils: with app version from manifest appVersion:1.0.0
06-22 20:28:26.106 459-459/xyz.nesting.tinkerdemo I/Tinker.VersionInfo: readVersionInfo file path:/data/user/0/xyz.nesting.tinkerdemo/tinker_server/e1b91ce001a2a7b0_version.info, appVersion: 1.0.0, uuid:ff6a9324-26aa-469d-a625-c6242ec7756c, abi:arm64-v8a, patchVersion:2, patchMd5:6682c40990d55dafa71c3b637f39d723, grayValue:7, crashTimes:0, retryTimes:0, applySuccess:0, patchSuccess:0
06-22 20:28:26.107 459-459/xyz.nesting.tinkerdemo D/Tinker.Debugger: debugger not attached cu == null
06-22 20:28:26.108 459-459/xyz.nesting.tinkerdemo I/Tinker.ServerClient: installTinkerServer, debug value: false, appVersion: 1.0.0, appKey: e1b91ce001a2a7b0
06-22 20:28:26.111 459-459/xyz.nesting.tinkerdemo W/Tinker.Tinker: tinker patch directory: /data/user/0/xyz.nesting.tinkerdemo/tinker
06-22 20:28:26.111 459-459/xyz.nesting.tinkerdemo I/Tinker.Tinker: try to install tinker, isEnable: true, version: 1.9.5
06-22 20:28:26.112 459-459/xyz.nesting.tinkerdemo I/Tinker.TinkerLoadResult: parseTinkerResult loadCode:-3, process name:xyz.nesting.tinkerdemo, main process:true, systemOTA:false, fingerPrint:Xiaomi/sagit/sagit:8.0.0/OPR1.170623.027/V9.6.2.0.OCACNFD:user/release-keys, oatDir:null, useInterpretMode:false
06-22 20:28:26.112 459-459/xyz.nesting.tinkerdemo W/Tinker.TinkerLoadResult: can't find patch file, is ok, just return
06-22 20:28:26.112 459-459/xyz.nesting.tinkerdemo I/Tinker.DefaultLoadReporter: patch loadReporter onLoadResult: patch load result, path:/data/user/0/xyz.nesting.tinkerdemo/tinker, code: -3, cost: 2ms
06-22 20:28:26.112 459-459/xyz.nesting.tinkerdemo W/Tinker.Tinker: tinker load fail!
06-22 20:28:26.113 459-459/xyz.nesting.tinkerdemo I/Tinker.TinkerPatch: Init TinkerPatch sdk success, version:1.2.5
06-22 20:28:26.357 459-459/xyz.nesting.tinkerdemo W/Tinker.UpgradePatchRetry: onPatchRetryLoad retry info not exist, just return

**Comment by DengZhouLi** [comment]
不好意思，是我自己没搞清楚！已经成功了

**Comment by hpuhsp** [comment]
能说下具体原因吗？谢谢~
