### ISSUE TITLE
下发补丁包后无法立即生效

### ISSUE THREAD

**Issue by huangboAndroid** [simpleton/tiny_httpclient#94]
全量下发后，重启应用无法立即生效，而且不同手机的生效时间也不一致，大概是什么原因呢。
ApplicationLike tinkerPatchApplicationLike = TinkerPatchApplicationLike.getTinkerPatchApplicationLike();

        // 初始化TinkerPatch SDK, 更多配置可参照API章节中的,初始化SDK
        if(tinkerPatchApplicationLike != null) {
            TinkerPatch.init(tinkerPatchApplicationLike)
                    .reflectPatchLibrary()
                    .setPatchRollbackOnScreenOff(true)
                    .setPatchRestartOnSrceenOff(true)
                    .setFetchDynamicConfigIntervalByHours(1);

            TinkerPatch.with().fetchPatchUpdate(true);
            TinkerPatch.with().fetchPatchUpdateAndPollWithInterval();
}

这是初始化代码

**Comment by simpleton** [comment]
http://tinkerpatch.com/Docs/dev
需要下载Debugtools 来做到实时生效
