### ISSUE TITLE
补丁包不能超过5M，不是说好不限制大小的吗

### ISSUE THREAD

**Issue by strongmanb** [simpleton/tiny_httpclient#95]
我现在账号是10W级别的，文档上说了不限制补丁包大小，但是我现在上传5M多点的补丁包的时候，提示“ 请选择文件 或者 检查补丁文件是否过大（大于 5M） ”！

现在这种问题要怎么解决？麻烦看到回复一下，谢谢

**Comment by simpleton** [comment]
5M对于补丁来说已经是一个相当大的阈值了。绝大部分的patch  都可以控制在1M以下的。一般超过5M一般上来讲都是patch
做的有点问题，欢迎在QQ 或者slack 上做更多的讨论

**Comment by strongmanb** [comment]
@simpleton 5M确实是有点大了，但每个产品可能有自己的需求，放开或增加这个限制会更友好一点，

**Comment by keven1119** [comment]
我的补丁只有60k，上传时提示 “请选择文件 或者 检查补丁文件是否过大（大于 5M）
”，但我已经选择了补丁文件

**Comment by simpleton** [comment]
那可能是BUG，你可以退出重新登录重试下。如果还有问题，可以在这里更新

**Comment by suixincry** [comment]
我的补丁只有10k，上传时提示 “请选择文件 或者 检查补丁文件是否过大（大于 5M）
”，但我已经选择了补丁文件

**Comment by simpleton** [comment]
@keven1119 @suixincry 现在还有问题么？

**Comment by suixincry** [comment]
@simpleton 现在没有了可以正常发布补丁

**Comment by wadeqlma23** [comment]
请选择文件 或者 检查补丁文件是否过大（大于 5M）
补丁8k

**Comment by simpleton** [comment]
可以清理cookie 重试下

**Comment by beiguancyc** [comment]
目前上传补丁提示请选择文件 或者 检查补丁文件是否过大（大于 5M）
