### ISSUE TITLE
付费和发票问题，tinkerpatch邮箱无人回复

### ISSUE THREAD

**Issue by Antipas** [simpleton/tiny_httpclient#97]
不好意思提问到这里了，admin@tinkerpatch.com一天都没有回复。
有具体的售前负责人联系方式么？可以开发票么？

**Comment by simpleton** [comment]
Hi 您好，不好意思。我印象邮箱里的邮件我都回复了。
你可以通过如下信息联系到我们
qq:    258699730
slack: https://slack.tinkerpatch.com
