### ISSUE TITLE
gradle 3.X版本 apkVariantData  api 过时问题

### ISSUE THREAD

**Issue by leojiao123** [simpleton/tiny_httpclient#99]
现在tinker 只能使用 3.x 以下的gradle 版本吗？ 使用 3.x 以上的gradle 版本会出现 Error:Could not get unknown property ‘apkVariantData’ for object of type com.android.build.gradle ， apkVariantDatag 该api在3.x以上被废弃了 ， 能做兼容吗

**Comment by simpleton** [comment]
应该使用3.x已经很久了，可以参考这个sample: https://github.com/TinkerPatch/tinkerpatch-easy-sample
